# This workflow will create a GitHub release every time a tag is pushed
name: Create GitHub Release

on:
  push:
    tags:
      - "v2.*"
      - "v3.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
